path :
    train_path : ../../data/train.csv
    dev_path : ../../data/dev.csv
    test_path : ../../data/dev.csv
    predict_path : ../../data/test.csv
    
data :
    shuffle : True
    augmentation : 
    
model : 
    model_name : monologg/koelectra-base-v3-discriminator
    saved_name : koelectra_model
    
train : 
    seed : 
    gpus : 1
    batch_size : 32
    max_epoch : 10
    learning_rate : 2e-5
